CREATE TABLE users (
     `id` int(11) NOT NULL AUTO_INCREMENT,
`first_name` varchar(255) NOT NULL DEFAULT '',
  `last_name` varchar(255) NOT NULL DEFAULT '',
  `email` varchar(250) NOT NULL DEFAULT '',
  `password` varchar(255) NOT NULL DEFAULT '',
 `forgot_request` varchar(60) NOT NULL DEFAULT '',
 `salt` varchar(60) NOT NULL DEFAULT '',
  `forgot_request_time` datetime DEFAULT '0000-00-00 00:00:00',
  `created_on_utc` datetime DEFAULT NULL,
  `created_on` datetime DEFAULT NULL,
  `created_on_utc` datetime DEFAULT NULL,
  `hash_id` varchar(32) NOT NULL DEFAULT '',
  `user_status` tinyint(4) NOT NULL DEFAULT '0',
  `user_role` char(3) NOT NULL DEFAULT 'U',
  `created_from` varchar(10) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  UNIQUE KEY `hash_id` (`hash_id`),
  KEY `first_name` (`first_name`),
  KEY `last_name` (`last_name`),
  KEY `created_on_utc` (`created_on_utc`),
  KEY `user_status` (`user_status`),
  KEY `type` (`type`),
  KEY `approved` (`approved`),
  KEY `created_from` (`created_from`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 |